CREATE TABLE "Manifesto" (
  "id" TEXT NOT NULL,
  "tenantId" TEXT NOT NULL,
  "empresaId" TEXT NOT NULL,
  "ambiente" "AmbienteFiscal" NOT NULL DEFAULT 'HOMOLOGACAO',
  "serie" INTEGER NOT NULL DEFAULT 1,
  "numero" INTEGER NOT NULL,
  "chave" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDENTE',
  "protocolo" TEXT,
  "motivo" TEXT,
  "xml" TEXT,
  "ufInicio" TEXT NOT NULL,
  "ufFim" TEXT NOT NULL,
  "municipioCarregaNome" TEXT NOT NULL,
  "municipioCarregaIbge" TEXT NOT NULL,
  "municipioDescargaNome" TEXT NOT NULL,
  "municipioDescargaIbge" TEXT NOT NULL,
  "veiculoPlaca" TEXT NOT NULL,
  "veiculoTara" INTEGER NOT NULL,
  "tipoRodado" TEXT NOT NULL DEFAULT '06',
  "tipoCarroceria" TEXT NOT NULL DEFAULT '02',
  "condutorNome" TEXT NOT NULL,
  "condutorCpf" TEXT NOT NULL,
  "chavesNfe" JSONB NOT NULL,
  "valorCarga" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "pesoBrutoKg" DECIMAL(14,4) NOT NULL DEFAULT 0,
  "encerradoEm" TIMESTAMP(3),
  "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "atualizadoEm" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Manifesto_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Manifesto_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "Manifesto_chave_key" ON "Manifesto"("chave");
CREATE INDEX "Manifesto_tenantId_empresaId_criadoEm_idx" ON "Manifesto"("tenantId", "empresaId", "criadoEm");
