/**
 * Lista de Serviços da Lei Complementar 116/2003 (anexo) — código `federalServiceCode`
 * usado na emissão de NFS-e. Lista federal fixa; descrições resumidas para seleção.
 * Itens vetados (3.01, 7.14, 7.15, 13.01, 17.07) foram omitidos por não serem utilizáveis.
 */

export type Lc116Item = {
  code: string;
  description: string;
};

export const LC116_LIST: Lc116Item[] = [
  // 1 — Informática
  { code: "1.01", description: "Análise e desenvolvimento de sistemas" },
  { code: "1.02", description: "Programação" },
  { code: "1.03", description: "Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos e congêneres" },
  { code: "1.04", description: "Elaboração de programas de computadores, inclusive jogos eletrônicos" },
  { code: "1.05", description: "Licenciamento ou cessão de direito de uso de programas de computação" },
  { code: "1.06", description: "Assessoria e consultoria em informática" },
  { code: "1.07", description: "Suporte técnico em informática (instalação, configuração e manutenção)" },
  { code: "1.08", description: "Planejamento, confecção, manutenção e atualização de páginas eletrônicas" },
  { code: "1.09", description: "Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto pela internet" },
  // 2 — Pesquisa e desenvolvimento
  { code: "2.01", description: "Serviços de pesquisas e desenvolvimento de qualquer natureza" },
  // 3 — Locação, cessão de direito de uso
  { code: "3.02", description: "Cessão de direito de uso de marcas e de sinais de propaganda" },
  { code: "3.03", description: "Exploração de salões de festas, centros de convenções, quadras, estádios e congêneres" },
  { code: "3.04", description: "Locação/cessão de uso de ferrovia, rodovia, postes, cabos, dutos e condutos" },
  { code: "3.05", description: "Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário" },
  // 4 — Saúde
  { code: "4.01", description: "Medicina e biomedicina" },
  { code: "4.02", description: "Análises clínicas, patologia, radioterapia, ressonância, radiologia, tomografia e congêneres" },
  { code: "4.03", description: "Hospitais, clínicas, laboratórios, prontos-socorros, ambulatórios e congêneres" },
  { code: "4.04", description: "Instrumentação cirúrgica" },
  { code: "4.05", description: "Acupuntura" },
  { code: "4.06", description: "Enfermagem, inclusive serviços auxiliares" },
  { code: "4.07", description: "Serviços farmacêuticos" },
  { code: "4.08", description: "Terapia ocupacional, fisioterapia e fonoaudiologia" },
  { code: "4.09", description: "Terapias destinadas ao tratamento físico, orgânico e mental" },
  { code: "4.10", description: "Nutrição" },
  { code: "4.11", description: "Obstetrícia" },
  { code: "4.12", description: "Odontologia" },
  { code: "4.13", description: "Ortóptica" },
  { code: "4.14", description: "Próteses sob encomenda" },
  { code: "4.15", description: "Psicanálise" },
  { code: "4.16", description: "Psicologia" },
  { code: "4.17", description: "Casas de repouso e de recuperação, creches, asilos e congêneres" },
  { code: "4.18", description: "Inseminação artificial, fertilização in vitro e congêneres" },
  { code: "4.19", description: "Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres" },
  { code: "4.20", description: "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos" },
  { code: "4.21", description: "Unidade de atendimento, assistência ou tratamento móvel e congêneres" },
  { code: "4.22", description: "Planos de medicina de grupo ou individual e convênios de assistência" },
  { code: "4.23", description: "Outros planos de saúde executados por serviços de terceiros" },
  // 5 — Veterinária
  { code: "5.01", description: "Medicina veterinária e zootecnia" },
  { code: "5.02", description: "Hospitais, clínicas, ambulatórios e prontos-socorros na área veterinária" },
  { code: "5.03", description: "Laboratórios de análise na área veterinária" },
  { code: "5.04", description: "Inseminação artificial, fertilização in vitro e congêneres (veterinária)" },
  { code: "5.05", description: "Bancos de sangue e de órgãos e congêneres (veterinária)" },
  { code: "5.06", description: "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos (veterinária)" },
  { code: "5.07", description: "Unidade de atendimento/tratamento móvel e congêneres (veterinária)" },
  { code: "5.08", description: "Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres" },
  { code: "5.09", description: "Planos de atendimento e assistência médico-veterinária" },
  // 6 — Cuidados pessoais, estética
  { code: "6.01", description: "Barbearia, cabeleireiros, manicuros, pedicuros e congêneres" },
  { code: "6.02", description: "Esteticistas, tratamento de pele, depilação e congêneres" },
  { code: "6.03", description: "Banhos, duchas, sauna, massagens e congêneres" },
  { code: "6.04", description: "Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas" },
  { code: "6.05", description: "Centros de emagrecimento, spa e congêneres" },
  { code: "6.06", description: "Aplicação de tatuagens, piercings e congêneres" },
  // 7 — Engenharia, construção, manutenção, limpeza, meio ambiente
  { code: "7.01", description: "Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres" },
  { code: "7.02", description: "Execução de obras de construção civil, hidráulica ou elétrica e instalação/montagem (exceto ICMS de mercadorias)" },
  { code: "7.03", description: "Elaboração de planos diretores, estudos de viabilidade, anteprojetos e projetos de engenharia" },
  { code: "7.04", description: "Demolição" },
  { code: "7.05", description: "Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres" },
  { code: "7.06", description: "Colocação/instalação de tapetes, carpetes, revestimentos, vidros, divisórias e congêneres" },
  { code: "7.07", description: "Recuperação, raspagem, polimento e lustração de pisos e congêneres" },
  { code: "7.08", description: "Calafetação" },
  { code: "7.09", description: "Varrição, coleta, remoção, tratamento, reciclagem e destinação final de lixo e resíduos" },
  { code: "7.10", description: "Limpeza, manutenção e conservação de vias, imóveis, piscinas, parques, jardins e congêneres" },
  { code: "7.11", description: "Decoração e jardinagem, inclusive corte e poda de árvores" },
  { code: "7.12", description: "Controle e tratamento de efluentes e de agentes físicos, químicos e biológicos" },
  { code: "7.13", description: "Dedetização, desinfecção, desinsetização, imunização, higienização e congêneres" },
  { code: "7.16", description: "Florestamento, reflorestamento, plantio, colheita, silvicultura e congêneres" },
  { code: "7.17", description: "Escoramento, contenção de encostas e serviços congêneres" },
  { code: "7.18", description: "Limpeza e dragagem de rios, portos, canais, lagos, represas e congêneres" },
  { code: "7.19", description: "Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo" },
  { code: "7.20", description: "Aerofotogrametria, cartografia, mapeamento, levantamentos topográficos e congêneres" },
  { code: "7.21", description: "Pesquisa, perfuração e serviços relacionados à exploração de petróleo, gás e minerais" },
  { code: "7.22", description: "Nucleação e bombardeamento de nuvens e congêneres" },
  // 8 — Educação
  { code: "8.01", description: "Ensino regular pré-escolar, fundamental, médio e superior" },
  { code: "8.02", description: "Instrução, treinamento, orientação pedagógica e avaliação de conhecimentos" },
  // 9 — Hospedagem e turismo
  { code: "9.01", description: "Hospedagem em hotéis, motéis, pensões e congêneres" },
  { code: "9.02", description: "Agenciamento, organização e execução de programas de turismo, viagens e congêneres" },
  { code: "9.03", description: "Guias de turismo" },
  // 10 — Intermediação
  { code: "10.01", description: "Agenciamento/corretagem de câmbio, seguros, cartões, planos de saúde e previdência privada" },
  { code: "10.02", description: "Agenciamento/corretagem de títulos, valores mobiliários e contratos" },
  { code: "10.03", description: "Agenciamento/corretagem de direitos de propriedade industrial, artística ou literária" },
  { code: "10.04", description: "Agenciamento/corretagem de leasing, franquia e factoring" },
  { code: "10.05", description: "Agenciamento/corretagem de bens móveis ou imóveis" },
  { code: "10.06", description: "Agenciamento marítimo" },
  { code: "10.07", description: "Agenciamento de notícias" },
  { code: "10.08", description: "Agenciamento de publicidade e propaganda" },
  { code: "10.09", description: "Representação de qualquer natureza, inclusive comercial" },
  { code: "10.10", description: "Distribuição de bens de terceiros" },
  // 11 — Guarda, estacionamento, armazenamento, vigilância
  { code: "11.01", description: "Guarda e estacionamento de veículos, aeronaves e embarcações" },
  { code: "11.02", description: "Vigilância, segurança ou monitoramento de bens, pessoas e semoventes" },
  { code: "11.03", description: "Escolta, inclusive de veículos e cargas" },
  { code: "11.04", description: "Armazenamento, depósito, carga, descarga, arrumação e guarda de bens" },
  // 12 — Diversões, lazer, entretenimento
  { code: "12.01", description: "Espetáculos teatrais" },
  { code: "12.02", description: "Exibições cinematográficas" },
  { code: "12.03", description: "Espetáculos circenses" },
  { code: "12.04", description: "Programas de auditório" },
  { code: "12.05", description: "Parques de diversões, centros de lazer e congêneres" },
  { code: "12.06", description: "Boates, taxi-dancing e congêneres" },
  { code: "12.07", description: "Shows, ballet, danças, desfiles, óperas, concertos, festivais e congêneres" },
  { code: "12.08", description: "Feiras, exposições, congressos e congêneres" },
  { code: "12.09", description: "Bilhares, boliches e diversões eletrônicas ou não" },
  { code: "12.10", description: "Corridas e competições de animais" },
  { code: "12.11", description: "Competições esportivas ou de destreza física ou intelectual" },
  { code: "12.12", description: "Execução de música" },
  { code: "12.13", description: "Produção de eventos, espetáculos, shows e congêneres" },
  { code: "12.14", description: "Fornecimento de música para ambientes, mediante transmissão" },
  { code: "12.15", description: "Desfiles de blocos carnavalescos, trios elétricos e congêneres" },
  { code: "12.16", description: "Exibição de filmes, espetáculos, shows, competições e congêneres" },
  { code: "12.17", description: "Recreação e animação, inclusive em festas e eventos" },
  // 13 — Fonografia, fotografia, reprografia
  { code: "13.02", description: "Fonografia ou gravação de sons, trucagem, dublagem, mixagem e congêneres" },
  { code: "13.03", description: "Fotografia e cinematografia, inclusive revelação, ampliação, cópia e congêneres" },
  { code: "13.04", description: "Reprografia, microfilmagem e digitalização" },
  { code: "13.05", description: "Composição gráfica, fotocomposição, clicheria, litografia e congêneres" },
  // 14 — Serviços relativos a bens de terceiros (oficina)
  { code: "14.01", description: "Lubrificação, limpeza, revisão, conserto e manutenção de máquinas, veículos e equipamentos (exceto peças, sujeitas ao ICMS)" },
  { code: "14.02", description: "Assistência técnica" },
  { code: "14.03", description: "Recondicionamento de motores (exceto peças, sujeitas ao ICMS)" },
  { code: "14.04", description: "Recauchutagem ou regeneração de pneus" },
  { code: "14.05", description: "Restauração, pintura, beneficiamento, lavagem, polimento e congêneres de objetos" },
  { code: "14.06", description: "Instalação e montagem de aparelhos, máquinas e equipamentos (material do usuário)" },
  { code: "14.07", description: "Colocação de molduras e congêneres" },
  { code: "14.08", description: "Encadernação, gravação e douração de livros, revistas e congêneres" },
  { code: "14.09", description: "Alfaiataria e costura, quando o material for fornecido pelo usuário final" },
  { code: "14.10", description: "Tinturaria e lavanderia" },
  { code: "14.11", description: "Tapeçaria e reforma de estofamentos em geral" },
  { code: "14.12", description: "Funilaria e lanternagem" },
  { code: "14.13", description: "Carpintaria e serralheria" },
  { code: "14.14", description: "Guincho intramunicipal, guindaste e içamento" },
  // 15 — Setor bancário/financeiro
  { code: "15.01", description: "Administração de fundos, consórcio, cartão de crédito/débito e congêneres" },
  { code: "15.02", description: "Abertura e manutenção de contas em geral" },
  { code: "15.03", description: "Locação e manutenção de cofres, terminais eletrônicos e equipamentos" },
  { code: "15.04", description: "Fornecimento ou emissão de atestados em geral" },
  { code: "15.05", description: "Cadastro, ficha cadastral, renovação cadastral e congêneres" },
  { code: "15.06", description: "Emissão de avisos, comprovantes e documentos; licenciamento/transferência de veículos" },
  { code: "15.07", description: "Acesso, movimentação e consulta a contas; fornecimento de saldo, extrato e informações" },
  { code: "15.08", description: "Contrato de crédito; análise de crédito; aval, fiança e congêneres" },
  { code: "15.09", description: "Arrendamento mercantil (leasing) de bens e serviços relacionados" },
  { code: "15.10", description: "Cobranças, recebimentos ou pagamentos em geral, inclusive por meio eletrônico" },
  { code: "15.11", description: "Devolução, protesto, sustação e manutenção de títulos e serviços relacionados" },
  { code: "15.12", description: "Custódia em geral, inclusive de títulos e valores mobiliários" },
  { code: "15.13", description: "Operações de câmbio em geral e serviços relacionados" },
  { code: "15.14", description: "Fornecimento e manutenção de cartão magnético, de crédito, de débito e congêneres" },
  { code: "15.15", description: "Compensação de cheques e títulos; serviços relacionados a depósito e saque" },
  { code: "15.16", description: "Ordens de pagamento/crédito; transferência de valores, dados e fundos" },
  { code: "15.17", description: "Emissão, devolução, sustação e cancelamento de cheques" },
  { code: "15.18", description: "Serviços relacionados a crédito imobiliário, avaliação e vistoria de imóvel" },
  // 16 — Transporte municipal
  { code: "16.01", description: "Transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros" },
  { code: "16.02", description: "Outros serviços de transporte de natureza municipal" },
  // 17 — Apoio técnico, administrativo, jurídico, contábil
  { code: "17.01", description: "Assessoria ou consultoria de qualquer natureza; fornecimento de dados e informações" },
  { code: "17.02", description: "Datilografia, digitação, secretaria, redação, tradução, apoio administrativo e congêneres" },
  { code: "17.03", description: "Planejamento, coordenação ou organização técnica, financeira ou administrativa" },
  { code: "17.04", description: "Recrutamento, agenciamento, seleção e colocação de mão de obra" },
  { code: "17.05", description: "Fornecimento de mão de obra, inclusive temporária" },
  { code: "17.06", description: "Propaganda e publicidade, inclusive promoção de vendas e campanhas" },
  { code: "17.08", description: "Franquia (franchising)" },
  { code: "17.09", description: "Perícias, laudos, exames técnicos e análises técnicas" },
  { code: "17.10", description: "Planejamento, organização e administração de feiras, exposições e congressos" },
  { code: "17.11", description: "Organização de festas e recepções; bufê (exceto alimentos/bebidas, sujeitos ao ICMS)" },
  { code: "17.12", description: "Administração em geral, inclusive de bens e negócios de terceiros" },
  { code: "17.13", description: "Leilão e congêneres" },
  { code: "17.14", description: "Advocacia" },
  { code: "17.15", description: "Arbitragem de qualquer espécie, inclusive jurídica" },
  { code: "17.16", description: "Auditoria" },
  { code: "17.17", description: "Análise de Organização e Métodos" },
  { code: "17.18", description: "Atuária e cálculos técnicos de qualquer natureza" },
  { code: "17.19", description: "Contabilidade, inclusive serviços técnicos e auxiliares" },
  { code: "17.20", description: "Consultoria e assessoria econômica ou financeira" },
  { code: "17.21", description: "Estatística" },
  { code: "17.22", description: "Cobrança em geral" },
  { code: "17.23", description: "Serviços relacionados a operações de faturização (factoring)" },
  { code: "17.24", description: "Apresentação de palestras, conferências, seminários e congêneres" },
  { code: "17.25", description: "Inserção de textos, desenhos e materiais de propaganda em qualquer meio" },
  // 18 a 40 — Itens de grupo único (principais)
  { code: "18.01", description: "Regulação de sinistros de seguros; inspeção e avaliação de riscos e congêneres" },
  { code: "19.01", description: "Distribuição e venda de bilhetes de loteria, bingos, apostas, sorteios e congêneres" },
  { code: "20.01", description: "Serviços portuários, ferroportuários, capatazia, armazenagem e congêneres" },
  { code: "20.02", description: "Serviços aeroportuários, capatazia, armazenagem e congêneres" },
  { code: "20.03", description: "Serviços de terminais rodoviários, ferroviários e metroviários" },
  { code: "21.01", description: "Serviços de registros públicos, cartorários e notariais" },
  { code: "22.01", description: "Exploração de rodovia mediante cobrança de pedágio e serviços relacionados" },
  { code: "23.01", description: "Programação e comunicação visual, desenho industrial e congêneres" },
  { code: "24.01", description: "Chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres" },
  { code: "25.01", description: "Funerais, fornecimento de caixão, transporte do corpo, embalsamento e congêneres" },
  { code: "25.02", description: "Translado intramunicipal e cremação de corpos e partes de corpos" },
  { code: "25.03", description: "Planos ou convênios funerários" },
  { code: "25.04", description: "Manutenção e conservação de jazigos e cemitérios" },
  { code: "25.05", description: "Cessão de uso de espaços em cemitérios para sepultamento" },
  { code: "26.01", description: "Coleta, remessa ou entrega de correspondências, documentos, bens ou valores; courier e congêneres" },
  { code: "27.01", description: "Serviços de assistência social" },
  { code: "28.01", description: "Serviços de avaliação de bens e serviços de qualquer natureza" },
  { code: "29.01", description: "Serviços de biblioteconomia" },
  { code: "30.01", description: "Serviços de biologia, biotecnologia e química" },
  { code: "31.01", description: "Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres" },
  { code: "32.01", description: "Serviços de desenhos técnicos" },
  { code: "33.01", description: "Desembaraço aduaneiro, comissários, despachantes e congêneres" },
  { code: "34.01", description: "Investigações particulares, detetives e congêneres" },
  { code: "35.01", description: "Reportagem, assessoria de imprensa, jornalismo e relações públicas" },
  { code: "36.01", description: "Serviços de meteorologia" },
  { code: "37.01", description: "Serviços de artistas, atletas, modelos e manequins" },
  { code: "38.01", description: "Serviços de museologia" },
  { code: "39.01", description: "Ourivesaria e lapidação (material fornecido pelo tomador)" },
  { code: "40.01", description: "Obras de arte sob encomenda" },
  // 99 — Casos especiais do Código de Tributação Nacional (NFS-e padrão nacional)
  { code: "99.01.01", description: "Serviços sem a incidência de ISSQN e ICMS" }
];

const LC116_SET = new Set(LC116_LIST.map((item) => item.code));

/** Valida se um código pertence à lista LC 116 (formato N.NN ou NN.NN). */
export function isValidLc116(code: string | null | undefined): boolean {
  return Boolean(code && LC116_SET.has(code.trim()));
}

/** Descrição do item LC 116, se existir. */
export function lc116Description(code: string | null | undefined): string | null {
  if (!code) return null;
  return LC116_LIST.find((item) => item.code === code.trim())?.description ?? null;
}
